### ISSUE TITLE
Add Order & Part search behavior to Packing Slip History

### ISSUE THREAD

**Issue by jarrilla** [conturo-prototyping/pack-ship-client#13]
Packing Slip History should have a similar search function to that of /shipments

See #4

**Comment by jarrilla** [comment]
Will need server endpoints as well

**Comment by joshplumley** [comment]
@jarrilla, I have this more or less working; however, I found a few issues that need to be resolved on the BE first, before this can fully be tested (https://github.com/conturo-prototyping/pack-ship-server/issues/11)

Also, how would you like the batch checkbox toggle to appear (if at all)?. I was assuming the search bar would be to the left and the checkboxes would be clustered to the right. If you do want them to appear, I think we may need the search endpoint to consider this as a parameter.

**Comment by jarrilla** [comment]
Oh, we should've removed those checkboxes from the history tab a while ago... The only thing filtering the history tab should be the search fields. Sorry!

I'll have a look at the back-end today, but my morning is pretty busy, so it won't be until the afternoon

**Comment by joshplumley** [comment]
I think we have the backend covered, I was just letting you know.
