### ISSUE TITLE
fix sort by date in both pages (history tabs)

### ISSUE THREAD

**Issue by jarrilla** [conturo-prototyping/pack-ship-client#17]
sort model should use `new Date(dateCreated).getTime()`

For example, right now a lexicographic comparison is being made so that 9/9/2021 > 5/25/2022

**Comment by jarrilla** [comment]
reverted changes from last MR. Observed apparent fix was due to back-end correctly parsing sort

**Comment by jbolles94** [comment]
@jarrilla Is this still an issue? If so, it sounds like this should be a backend fix. Is that correct? Just want to be sure I have the right idea before I pursue it

**Comment by jarrilla** [comment]
So, it seems like it is only an issue in Packing Slips now, where it is entirely a front-end function.

However, once we change the search to be back-end driven, it may be fixed entirely.
